# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WSPR.IO
email: will@wspr.io
description: > # this means to ignore newlines until "baseurl:"
  Irreverance by William Samuel Parker Robertson.
  Wannabe academic in engineering (magnetic levitation, vibration control, mechatronics, biomechanics).
  Member of the LaTeX3 Project.
  On his way to becoming a grown-up.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wspr.io" # the base hostname & protocol for your site
twitter_username: wspr
github_username:  wspr



# Build settings
markdown: kramdown

# Outputting
permalink:     /:categories/:title

# Collections
collections:
  pages:
    output: true
    permalink: /:path
